server:
  port: 3344
  
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: git@github.com:zsllsz/springcloud-config.git # github仓库地址
          search-paths:
          - springcloud-config # 仓库名
      label: master # 分支
  # mq相关配置
  rabbitmq:
    host: 192.168.0.106
    port: 5672
    username: admin
    password: admin
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
      
# bus配置
management:
  endpoints:
    web:
      exposure:
        include:
        - 'bus-refresh'