server:
  port: 8001

spring:
  application:
    name: cloud-payment-service #提交到注册中心的微服务名称
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1 # 采样率值介于0和1之间，1表示全部采集
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db2020?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123
    
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zhusl.springcloud.entities
  
eureka:
  client:
    register-with-eureka: true # 将自己注册进eureka
    fetch-registry: true # 从eureka抓取自己的注册信息
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka#,http://eureka7002.com:7002/eureka #eureka server所在的主机和端口
  instance:
    instance-id: payment8001
    prefer-ip-address: true #显示IP信息
    lease-expiration-duration-in-seconds: 1 # eureka服务端收到最后一次心跳后等待的时间上限，默认90秒
    lease-renewal-interval-in-seconds: 1 # 8001服务向eureka注册中心发送心跳的时间间隔，默认30秒